Description: >
  Ybrahin Martinez - IAM Jenkins Pipelines

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  GroupName:
    Description: Name of group
    Type: String
    Default: jenkins-group
  
  UserName:
    Description: Name of user
    Type: String
    Default: jenkins

Resources:

  JenkinsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: "UserJenkins"
        PasswordResetRequired: true

  JenkinsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  UserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-Role
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  JenkinsPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-Jenkins-Policies
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - "ec2:DescribeAddresses"
          - "ec2:AllocateAddress"
          - "ec2:DescribeInstances"
          - "ec2:AssociateAddress"
          Resource: '*'
        - Effect: Allow
          Action:
          - "iam:ChangePassword"
          Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:user/*'
      Groups:
        - !Ref JenkinsGroup
      Roles:
        - !Ref UserRole

  AddUserGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref JenkinsGroup
      Users:
        - !Ref JenkinsUser

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
      - !Ref UserRole

  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref JenkinsUser

Outputs:

  JenkinsRol:
    Description: Jenikins Rol
    Value: !GetAtt UserRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-JenkinsRol

  InstanceProfile:
    Description: Instance profile of Rol
    Value: !Ref InstanceProfile
    Export:
      Name: !Sub ${EnvironmentName}-InstanceProfile

  AccessKey:
    Value: !Ref Keys
    Description: AWSAccessKeyId of new user
    
  SecretKey:
    Value: !GetAtt Keys.SecretAccessKey
    Description: AWSSecretAccessKey of new user